
Type: AWS::S3::BucketPolicy
Properties: 
  Bucket: 
    Ref: s3DeploymentBucket
  PolicyDocument: 
    Statement: 
      - Action: 
          - "s3:GetObject"
        Effect: "Allow"
        Resource: !Join ["", ["arn:aws:s3:::", !Ref s3DeploymentBucket, "/*"]]
        Principal: "*"
        Sid: "PublicReadGetObject" 
         