Type: AWS::S3::Bucket
Properties: 
  BucketName: ${self:custom.environment.serverlessdocs-website-bucket}-${opt:stage}
  PublicAccessBlockConfiguration:
    BlockPublicAcls: false
    BlockPublicPolicy: false
    IgnorePublicAcls: false
    RestrictPublicBuckets: false
  CorsConfiguration: 
    CorsRules:
      -
        AllowedOrigins:
          - '*'
        AllowedHeaders:
          - '*'
        AllowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
        ExposedHeaders:
          - ETag
        
  
